fn main() {
    windows::build!(
        Windows::Win32::System::SystemServices::{
            HANDLE,
            TRUE,
            FALSE
        },
        Windows::Win32::System::WindowsProgramming::{
            GetStdHandle,
            STD_OUTPUT_HANDLE,
            STD_INPUT_HANDLE
        },
        Windows::Win32::System::Console::{
            SetConsoleWindowInfo,
            SetCurrentConsoleFontEx,
            SetConsoleScreenBufferSize,
            SetConsoleActiveScreenBuffer,
            GetConsoleScreenBufferInfoEx,
            SetConsoleScreenBufferInfoEx,
            SetConsoleWindowInfo,
            SetConsoleMode,
            GetConsoleWindow,
            WriteConsoleOutputW,
            FlushConsoleInputBuffer,
            GetNumberOfConsoleInputEvents,
            ReadConsoleInputW,
            SetConsoleTitleW,
            SMALL_RECT,
            CONSOLE_FONT_INFOEX,
            COORD,
            CONSOLE_SCREEN_BUFFER_INFOEX,
            CONSOLE_MODE,
            ENABLE_EXTENDED_FLAGS,
            CHAR_INFO,
            INPUT_RECORD,
            WINDOW_BUFFER_SIZE_EVENT
        },
        Windows::Win32::UI::WindowsAndMessaging::{
            GetWindowLongW,
            SetWindowLongW,
            GetSystemMenu,
            SetLayeredWindowAttributes,
            GWL_STYLE,
            WS_MAXIMIZEBOX,
            WS_SIZEBOX,
            LWA_ALPHA,
            VK_UP,
            VK_LEFT,
            VK_RIGHT
        },
        Windows::Win32::Graphics::Gdi::{
            FF_DONTCARE,
            /*FF_MODERN,
            TMPF_TRUETYPE,
            TMPF_VECTOR,*/
            FW_NORMAL
        },
        Windows::Win32::UI::KeyboardAndMouseInput::GetAsyncKeyState
    );
}